#!/usr/bin/env python3
"""Subset Fraunces down to the glyphs this app can actually display.

Output: fonts/fraunces-subset.woff2

The full variable font is 360KB. The app only ever shows Latin letters, digits
and a short list of punctuation, so subsetting it is most of an order of
magnitude for free — and the app is bundled offline, so every byte is a byte in
the APK.

Two axes are pinned rather than shipped:
  opsz  pinned high — the display face is only used large.
  WONK  pinned on   — the quirky alternates are the reason to use this face.
SOFT is dropped (defaults to 0) and wght is kept, because headings and the huge
quiz word want different weights.

Fraunces is Copyright 2018 The Fraunces Project Authors, SIL Open Font License
1.1. tools/vendor/Fraunces-OFL.txt is the licence; fonts/OFL.txt ships with the
app, as the licence requires.
"""

import base64
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "vendor", "Fraunces.ttf")
LICENCE_SRC = os.path.join(HERE, "vendor", "Fraunces-OFL.txt")
OUT_DIR = os.path.join(ROOT, "fonts")
OUT = os.path.join(OUT_DIR, "fraunces-subset.woff2")
CSS_OUT = os.path.join(OUT_DIR, "fraunces.css")

# Everything the interface can put on screen in the display face: words and
# stems (both cases), counts and scores, and the punctuation the copy uses.
CHARS = (
    "abcdefghijklmnopqrstuvwxyz"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "0123456789"
    " .,;:!?'\"-–—/%+&()[]…‘’“”·×"
)


def main():
    if not os.path.exists(SRC):
        sys.exit(f"missing {SRC} — see the URL in ANDROID.md / this file's docstring")
    os.makedirs(OUT_DIR, exist_ok=True)

    # 1. Pin the axes we have an opinion about, keeping weight variable so
    #    headings and the huge quiz word can differ without a second file.
    #    wght=100:400:900 is min:default:max — the source font defaults to 900,
    #    which would make every unstyled use bold.
    partial = os.path.join(OUT_DIR, ".fraunces-partial.ttf")
    subprocess.run(
        [sys.executable, "-m", "fontTools.varLib.instancer", SRC,
         "opsz=100", "WONK=1", "SOFT=0", "wght=100:400:900",
         "--output=" + partial],
        check=True, capture_output=True,
    )

    # 2. Throw away every glyph the interface cannot display.
    subprocess.run(
        [sys.executable, "-m", "fontTools.subset", partial,
         "--text=" + CHARS,
         "--output-file=" + OUT,
         "--flavor=woff2",
         "--layout-features=kern,liga,calt",
         "--no-hinting",
         "--name-IDs=1,2,3,4,5,6",
         "--drop-tables+=DSIG"],
        check=True, capture_output=True,
    )
    os.remove(partial)

    # 3. Embed it as a data: URI.
    #
    #    Chrome refuses cross-origin font fetches from file:// — opening
    #    index.html by double-clicking it would silently fall back to Georgia,
    #    which is the one place the design cannot afford to fall back. A data:
    #    URI is same-origin by definition and loads everywhere: from file://,
    #    from a server, and inside the Capacitor WebView. It costs ~33% in
    #    base64 overhead, which on a 26KB font is a rounding error.
    b64 = base64.b64encode(open(OUT, "rb").read()).decode("ascii")
    css = (
        "/* Generated by tools/build_font.py - do not edit by hand.\n"
        "   Fraunces, subset and embedded. Loaded before css/app.css.\n"
        "\n"
        "   Copyright 2018 The Fraunces Project Authors\n"
        "   (https://github.com/undercasetype/Fraunces), SIL Open Font License\n"
        "   1.1. Full licence in fonts/OFL.txt, which ships with the app. */\n"
        "@font-face {\n"
        '  font-family: "Fraunces";\n'
        '  src: url("data:font/woff2;base64,' + b64 + '") format("woff2");\n'
        "  font-weight: 100 900;\n"
        "  font-style: normal;\n"
        "  font-display: block;\n"
        "}\n"
    )
    open(CSS_OUT, "w", encoding="ascii").write(css)

    shutil.copyfile(LICENCE_SRC, os.path.join(OUT_DIR, "OFL.txt"))

    before = os.path.getsize(SRC)
    after = os.path.getsize(OUT)
    print(f"Fraunces  {before/1024:.0f} KB  ->  {after/1024:.1f} KB subset woff2")
    print(f"          {len(CHARS)} characters kept")
    print(f"embedded  {os.path.getsize(CSS_OUT)/1024:.1f} KB as fonts/fraunces.css")
    print("wrote fonts/OFL.txt")


if __name__ == "__main__":
    main()
