#!/usr/bin/env python3
"""Build the on-device lexicon from the ENABLE word list, plus a small supplement.

Input : tools/enable1.txt     (public-domain ENABLE list, see PROVENANCE.md)
        tools/supplement.json (words valid in NWL2023 but absent from ENABLE)
Output: data/lexicon.js       (globals WT_LEX and WT_LEX_ADDED, lengths 1-8)

Storage format: one fixed-width string per word length. A length-3 bucket is
just every 3-letter word concatenated ("aahaalaas..."), so the file carries no
separators and the app slices it back apart at load. Smaller than JSON, and it
parses into a Set in a few milliseconds even on a phone.
"""

import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "enable1.txt")
SUPP = os.path.join(HERE, "supplement.json")
OUT = os.path.join(ROOT, "data", "lexicon.js")

MIN_LEN, MAX_LEN = 1, 8
# Board play needs longer words; they go in their own file, loaded on demand.
LONG_MIN, LONG_MAX = 9, 15

# Recorded so a future build can prove it used the same source file.
EXPECTED_SHA256 = "3f16130220645692ed49c7134e24a18504c2ca55b3c012f7290e3e77c63b1a89"
EXPECTED_TOTAL = 172823


def main():
    raw = open(SRC, "rb").read()
    digest = hashlib.sha256(raw).hexdigest()
    words = [w.strip().lower() for w in raw.decode("ascii").splitlines() if w.strip()]

    print(f"source sha256 : {digest}")
    print(f"source words  : {len(words)}")
    if digest != EXPECTED_SHA256:
        print("  ! sha256 differs from the recorded source file", file=sys.stderr)
    if len(words) != EXPECTED_TOTAL:
        print(f"  ! expected {EXPECTED_TOTAL} words", file=sys.stderr)

    if any(not w.isalpha() or not w.isascii() for w in words):
        bad = [w for w in words if not w.isalpha() or not w.isascii()][:10]
        print(f"  ! non-alphabetic entries present: {bad}", file=sys.stderr)

    # The supplement: words valid in the current tournament list that ENABLE
    # lacks. Kept in its own file, and listed in the output, so the lexicon is
    # never quietly something other than ENABLE.
    supplement = json.load(open(SUPP, encoding="utf-8"))
    added = sorted(set(supplement["add"]["twos"] + supplement["add"]["threes"]))
    already = [w for w in added if w in set(words)]
    if already:
        print(f"  ! supplement entries already in ENABLE (drop them): {already}", file=sys.stderr)
    print(f"supplement    : {len(added)} words")

    base = set(words)
    buckets = {n: [] for n in range(MIN_LEN, MAX_LEN + 1)}
    for w in base | set(added):
        if MIN_LEN <= len(w) <= MAX_LEN:
            buckets[len(w)].append(w)

    payload = {}
    total = 0
    for n in range(MIN_LEN, MAX_LEN + 1):
        ws = sorted(set(buckets[n]))
        payload[str(n)] = "".join(ws)
        total += len(ws)
        extra = len([w for w in added if len(w) == n])
        print(f"  {n}-letter: {len(ws):>6}" + (f"  (+{extra} added)" if extra else ""))
    print(f"shipped words : {total}")

    body = json.dumps(payload, separators=(",", ":"))
    js = (
        "/* Generated by tools/build_data.py - do not edit by hand.\n"
        "   Source: ENABLE word list (public domain). See PROVENANCE.md.\n"
        f"   Source sha256: {digest}\n"
        f"   Plus {len(added)} words from tools/supplement.json (valid in NWL2023,\n"
        "   absent from ENABLE). WT_LEX_ADDED lists exactly which ones.\n"
        f"   Words shipped: {total} (lengths {MIN_LEN}-{MAX_LEN})\n"
        "   Each value is every word of that length concatenated, no separators. */\n"
        f"var WT_LEX = {body};\n"
        f"var WT_LEX_ADDED = {json.dumps(added, separators=(',', ':'))};\n"
    )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="ascii").write(js)
    print(f"wrote {OUT} ({os.path.getsize(OUT) / 1024:.0f} KB)")

    # The long tail, for the board engine. Anything over 15 letters is dropped:
    # it cannot fit on a 15x15 board.
    long_buckets = {}
    for w in base | set(added):
        if LONG_MIN <= len(w) <= LONG_MAX:
            long_buckets.setdefault(str(len(w)), []).append(w)
    long_payload = {
        k: "".join(sorted(v))
        for k, v in sorted(long_buckets.items(), key=lambda kv: int(kv[0]))
    }
    long_total = sum(len(v) // int(k) for k, v in long_payload.items())
    dropped = len([w for w in base if len(w) > LONG_MAX])
    print(f"long words    : {long_total} (lengths {LONG_MIN}-{LONG_MAX})")
    print(f"  dropped     : {dropped} words over {LONG_MAX} letters (cannot fit a board)")
    long_js = (
        "/* Generated by tools/build_data.py - do not edit by hand.\n"
        f"   The {LONG_MIN}-{LONG_MAX} letter words, for board play. Words longer than {LONG_MAX}\n"
        "   letters are dropped: they cannot fit on a 15x15 board.\n"
        "\n"
        "   Kept apart from data/lexicon.js because the study modes never need\n"
        "   these, and js/lexicon.js only unpacks this file when something asks\n"
        "   about a word longer than eight letters.\n"
        f"   Words: {long_total}. Each value is every word of that length\n"
        "   concatenated, no separators. */\n"
        "var WT_LEX_LONG = "
        + json.dumps(long_payload, separators=(",", ":"))
        + ";\n"
    )
    long_out = os.path.join(ROOT, "data", "lexicon_long.js")
    open(long_out, "w", encoding="ascii").write(long_js)
    print(f"wrote {long_out} ({os.path.getsize(long_out) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
